#!/bin/sh /etc/rc.common
# Copyright (C) 2013-2014 OpenWrt.org

START=00
STOP=90

RTC_DEV=/dev/rtc0
HWCLOCK=/sbin/hwclock
TIME_FILE=/etc/soft.clock

boot() {
	hwclock_load
	local soft_time="$(find_soft_time)"
	local hard_time="$(date +%s)"
	if [ $hard_time -lt $soft_time ]; then
		date -s @$soft_time
		hwclock_save
		save_soft_time
	fi
}

start() {
	hwclock_load
}

stop() {
	hwclock_save
	save_soft_time
}

hwclock_load() {
	[ -e "$RTC_DEV" ] && [ -e "$HWCLOCK" ] && $HWCLOCK -s -u -f $RTC_DEV
}

hwclock_save(){
	[ -e "$RTC_DEV" ] && [ -e "$HWCLOCK" ] && $HWCLOCK -w -u -f $RTC_DEV && \
		logger -t sysfixtime "saved '$(date)' to $RTC_DEV"
}

save_soft_time(){
	touch $TIME_FILE
}

find_soft_time() {
	local newest
	if [ -e "$TIME_FILE" ]; then
		newest=$TIME_FILE
	else
		local file
		for file in $( find /etc -type f ) ; do
			[ -z "$newest" -o "$newest" -ot "$file" ] && newest=$file
		done
	fi
	date -r "$newest" +%s
}
